#!/usr/bin/env bash

## Import a database from a Pantheon environment.
##
## Usage: this function is included in various custom fin commands via:
## source "${PROJECT_ROOT}/.docksal/commands/common/import_database.sh"

import_database ()
{
  local dest="${PROJECT_ROOT}/database_dumps"
  if [[ ! -d $dest ]]; then
    create_database_folder
  fi
  echo "PROJECT_NAME is: ${PROJECT_NAME}"
  cd "${PROJECT_ROOT}"
  echo "Deleting old database dumps..."
  rm -f database_dumps/aq.to.sql > /dev/null
  rm -f database_dumps/aq.to.sql.gz > /dev/null
  echo "Creating copy of aqto dev server db..."
  # For this lets ssh onto our ${AQTO_SERVER_IP} server, ${AQTO_APP_LOCATION}, run ./vendor/bin/drush sql-dump --result-file=${SERVER_DB_BACKUPS_LOCATION}/aq.to.sql, we'll rysnc it down then delete it from server after we fin import.
  ssh aqto-dev@${AQTO_SERVER_IP} -p22 <<EOF
cd ${AQTO_APP_LOCATION}
./vendor/bin/drush sql-dump --result-file=${SERVER_DB_BACKUPS_LOCATION}/aq.to.sql
EOF
  rsync -avz aqto-dev@${AQTO_SERVER_IP}:${SERVER_DB_BACKUPS_LOCATION}/aq.to.sql "${PROJECT_ROOT}/database_dumps/aq.to.sql"
  ssh aqto-dev@${AQTO_SERVER_IP} -p22 <<EOF
rm -f ${SERVER_DB_BACKUPS_LOCATION}/aq.to.sql
EOF

  echo "Fixing collation in the SQL dump..."
  sed -i '' 's/utf8mb4_0900_ai_ci/utf8mb4_general_ci/g' "${PROJECT_ROOT}/database_dumps/aq.to.sql"

  echo "Extracting and importing copy of aqto dev server db..."
  fin db import "database_dumps/aq.to.sql"
}

create_database_folder()
{
  cd "${PROJECT_ROOT}"
  mkdir database_dumps
}

#-------------------------- Execution --------------------------------

import_database
