name: Update latest configs and Features revert from LIVE

on:
  workflow_dispatch:

jobs:
  setup_lamp_environment:
    runs-on: ubuntu-latest
    env:
      path_to_site_codebase_on_runner: ${{ github.workspace }}  # Base path where repo is cloned

    services:
      mariadb:
        image: mariadb:10.5
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: drupal
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup SSH
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SERVER_SSH_KEY }}
          if_key_exists: replace
          config: |
            LogLevel=quiet
            Host *
            StrictHostKeyChecking=no
            PasswordAuthentication no
            PubkeyAuthentication yes
          known_hosts: |
            127.0.0.1
      - name: Set up PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, curl, zip
          coverage: none

      - name: Setup Apache
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository ppa:ondrej/php
          sudo apt-get update
          sudo apt-get install -y apache2 libapache2-mod-php8.2 php8.2-mysql
          sudo sed -i 's#/var/www/html#${{ env.path_to_site_codebase_on_runner }}/web#g' /etc/apache2/sites-available/000-default.conf
          sudo sed -i 's#/var/www/html#${{ env.path_to_site_codebase_on_runner }}/web#g' /etc/apache2/sites-available/default-ssl.conf
          sudo systemctl restart apache2

      - name: Create settings.local.php
        run: |
          cat <<EOF > ${{ env.path_to_site_codebase_on_runner }}/web/sites/default/settings.local.php
          <?php
          \$databases['default']['default'] = array(
            'driver' => 'mysql',
            'database' => 'drupal',
            'username' => 'root',
            'password' => 'root',
            'host' => '127.0.0.1',
            'port' => '3306',
            'prefix' => '',
            'namespace' => 'Drupal\\Core\\Database\\Driver\\mysql',
            'driver' => 'mysql',
          );
          EOF
          chmod 755 ${{ env.path_to_site_codebase_on_runner }}/web/sites/default/settings.local.php

      - name: Install Composer Dependencies
        run: |
          cd ${{ env.path_to_site_codebase_on_runner }}
          composer install --no-progress --no-interaction

      - name: Initialize Drupal Installation
        run: |
          cd ${{ env.path_to_site_codebase_on_runner }}
          # It's a fresh site at this point with fresh db, could theoretically do any ops on the fresh codebase e.g. site install:
          # ./vendor/bin/drush si -y
          sudo chown -R www-data:www-data ${{ env.path_to_site_codebase_on_runner }}/web

      - name: Start Apache Service
        run: sudo systemctl start apache2

      - name: Sync Database and Update Config
        env:
          SSH_USER: aqto-dev
          SSH_HOST: ${{ secrets.SERVER_IP_ADDRESS }}
          SSH_PORT: 22
          SERVER_APP_LOCATION: ${{ secrets.SERVER_APP_LOCATION }}
        run: |
          ssh $SSH_USER@$SSH_HOST -p$SSH_PORT -v <<EOF
          cd $SERVER_APP_LOCATION
          ./vendor/bin/drush sql-dump --result-file=/tmp/dump.sql
          EOF
          cd ${{ env.path_to_site_codebase_on_runner }}
          scp -P$SSH_PORT $SSH_USER@$SSH_HOST:/tmp/dump.sql .
      
          # Apply the sed fix to the dump file
          sed -i 's/utf8mb4_0900_ai_ci/utf8mb4_unicode_ci/g' dump.sql

          # Get our git setup for the commits ahead.
          git config --global user.name "aqto-auto"
          git config --global user.email "tyler@tylerfahey.com"
      
          # Drop the fresh install db and import the live site dump.
          ./vendor/bin/drush sql-drop -y
          ./vendor/bin/drush sql-cli < dump.sql

          # First, capture all the current config from the fresh live site.
          ./vendor/bin/drush cex -y
          git add .
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update config from live"
            git push origin main
          else
            echo "No changes to commit"
          fi

          # Now, we can enforce any Features that we may have updated or erroneously been reverted on live site.
          ./vendor/bin/drush fr aqto_page -y
          # Add + commit the resulting changes.
          git add .
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Revert aqto_page feature from live site."
            git push origin main
          else
            echo "No changes to commit"
          fi
      - name: Run a composer update and a drush updb -y
        run: |
          cd ${{ env.path_to_site_codebase_on_runner }}
          composer update --no-progress --no-interaction
          git add .
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Run a composer update"
            git push origin main
          else
            echo "No changes to commit"
          fi
          ./vendor/bin/drush updb -y
          ./vendor/bin/drush cex -y
          git add .
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Export config post update"
            git push origin main
          else
            echo "No changes to commit"
          fi
      - name: Deploy
        env:
          SSH_USER: aqto-dev
          SSH_HOST: ${{ secrets.SERVER_IP_ADDRESS }}
          SSH_PORT: 22
          SERVER_APP_LOCATION: ${{ secrets.SERVER_APP_LOCATION }}
        run: |
          ssh $SSH_USER@$SSH_HOST -p$SSH_PORT -v <<EOF
          cd $SERVER_APP_LOCATION
          git pull
          composer install --no-progress --no-interaction
          # Do a sql-dump to a folder on server /srv/users/aqto-dev/apps/aqto-dev/backups that we'll replace on each deploy.
          # This way we can always revert to the last known good state.
          ./vendor/bin/drush sql-dump --result-file=/srv/users/aqto-dev/apps/aqto-dev/backups/dump.sql
          # Now we config import any changes to the live site.
          ./vendor/bin/drush cim -y
          EOF
