name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SERVER_SSH_KEY }}
          if_key_exists: replace
          config: |
            LogLevel=quiet
            Host *
            StrictHostKeyChecking=no
            PasswordAuthentication no
            PubkeyAuthentication yes
            Host *.drush.in
            StrictHostKeyChecking no
          known_hosts: |
            127.0.0.1
      - name: Deploy
        env:
          SSH_USER: aqto-dev
          SSH_HOST: ${{ secrets.SERVER_IP_ADDRESS }}
          SSH_PORT: 22
          SERVER_APP_LOCATION: ${{ secrets.SERVER_APP_LOCATION }}
        run: |
          ssh $SSH_USER@$SSH_HOST -p$SSH_PORT -v <<EOF
          cd $SERVER_APP_LOCATION
          # First lets sql dump to a "${{ secrets.SERVER_APP_LOCATION }}/../backups/deploy-pre-backup.sql" file
          ./vendor/bin/drush sql-dump --result-file="${{ secrets.SERVER_APP_LOCATION }}/../backups/deploy-pre-backup.sql"
          # Next, lets chmod things like web/sites/default, web/sites/default/services.yml, web/sites/default/settings.default.php, to be writable so the git pull and subsequent composer updates dont weirdly fail
          chmod -R 777 web/sites/default
          # Now lets git pull and composer install
          git clean -df
          git reset --hard
          git checkout main
          git pull
          composer install --no-progress --no-interaction
          # Now lets drush cache rebuild + drush config import + drush updb -y
          ./vendor/bin/drush cr -y
          ./vendor/bin/drush cim -y
          ./vendor/bin/drush updb -y
          # Now lets chmod things like web/sites/default, web/sites/default/services.yml, web/sites/default/settings.default.php, to be read-only again, just the specific files that matter.
          chmod 644 web/sites/default/services.yml
          chmod 644 web/sites/default/settings.default.php
          chmod 755 web/sites/default
          

          EOF
