name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SERVER_SSH_KEY }}
          if_key_exists: replace
          config: |
            LogLevel=quiet
            Host *
            StrictHostKeyChecking=no
            PasswordAuthentication no
            PubkeyAuthentication yes
            Host *.drush.in
            StrictHostKeyChecking no
          known_hosts: |
            127.0.0.1
      - name: Deploy
        env:
          SSH_USER: aqto-dev
          SSH_HOST: ${{ secrets.SERVER_IP_ADDRESS }}
          SSH_PORT: 22
          SERVER_APP_LOCATION: ${{ secrets.SERVER_APP_LOCATION }}
        run: |
          ssh $SSH_USER@$SSH_HOST -p$SSH_PORT -v <<EOF
          cd $SERVER_APP_LOCATION
          # First lets sql dump to a "${{ secrets.SERVER_APP_LOCATION }}/../backups/deploy-pre-backup.sql" file
          ./vendor/bin/drush sql-dump --result-file="${{ secrets.SERVER_APP_LOCATION }}/../backups/deploy-pre-backup.sql"
          git pull
          composer install --no-progress --no-interaction
          # Now lets drush cache rebuild + drush config import + drush updb -y
          ./vendor/bin/drush cr -y
          ./vendor/bin/drush cim -y
          ./vendor/bin/drush updb -y
          EOF
